added support for separate ephemeral storage
chainzero/provider-build-scripts pull request #21
Opened 2024-12-30 16:16 UTC by shimpa1

TODO:

upgrade_k3s.sh does not work correctly

2025-01-03 15:17 UTC, andy108369 requested changes

2025-01-03 15:17 UTC, ghost commented on providerBuild.sh
> +DEFAULT_IMAGEFS_DIR="/var/lib/containerd"
@shimpa1 I think you want to update the `DEFAULT_IMAGEFS_DIR` to `/var/lib/rancher/k3s` since:
- `/var/lib/containerd` for kubespray based cluster deployments.
- `/var/lib/rancher/k3s` - for K3S based cluster deployments. (it then creates automatically `agent/containerd` subdir, e.g. `/var/lib/rancher/k3s/agent/containerd`)

2025-01-03 15:17 UTC, ghost commented on k3sAndProviderServices.sh
> +      containerd_storage="--data-dir=$OPTARG"
Let's name it `imagefs_dir` instead of `containerd_storage`

2025-01-03 15:17 UTC, ghost commented on k3sAndProviderServices.sh
> +      kubelet_storage="--kubelet-arg=root-dir=$OPTARG"
Let's name it `nodefs_dir` instead of the `kubelet_storage`

2025-01-03 15:17 UTC, ghost commented on workerNode.sh
> +      kubelet_storage="--kubelet-arg=root-dir=$OPTARG"
Let's name it `nodefs_dir` instead of the `kubelet_storage`

2025-01-03 15:17 UTC, ghost commented on workerNode.sh
> +      containerd_storage="--data-dir=$OPTARG"
Let's name it `imagefs_dir` instead of `containerd_storage`

2025-01-03 15:17 UTC, andy108369 commented on providerBuild.sh
> +EXECSTART=$(grep "ExecStart=" "$SERVICE_FILE" -A 10)
`systemctl show k3s.service --property=ExecStart --no-pager -l` would probably be a better option instead of relying on `-A 10` to be sufficient; some providers may have multiple options/ more SAN records.

Tested on `root@node1-h100-hou-dd-akash-pub`:
```
root@node1:~# systemctl show k3s.service --property=ExecStart --no-pager -l | grep -o "\--kubelet-arg=root-dir=[^ ]*"
--kubelet-arg=root-dir=/data/kubelet
root@node1:~# 
root@node1:~# systemctl show k3s.service --property=ExecStart --no-pager -l | grep -o "\--data-dir=[^ ]*"
--data-dir=/data/containerd
root@node1:~# 
```

2025-01-03 15:17 UTC, andy108369 commented on providerBuild.sh
> +    helm install --create-namespace -n rook-ceph rook-ceph rook-release/rook-ceph --version 1.14.0 -f ~/provider/rook-ceph-operator.values.yml
please update `rook-ceph` & `rook-ceph-cluster` charts to `v1.16.1` in the scripts.

2025-01-03 17:15 UTC, shimpa1 commented on providerBuild.sh
> +DEFAULT_IMAGEFS_DIR="/var/lib/containerd"
done thank you

2025-01-03 17:17 UTC, shimpa1 commented on k3sAndProviderServices.sh
> +      kubelet_storage="--kubelet-arg=root-dir=$OPTARG"
done

2025-01-03 17:18 UTC, shimpa1 commented on workerNode.sh
> +      containerd_storage="--data-dir=$OPTARG"
done

2025-01-03 17:19 UTC, shimpa1 commented on providerBuild.sh
> +    helm install --create-namespace -n rook-ceph rook-ceph rook-release/rook-ceph --version 1.14.0 -f ~/provider/rook-ceph-operator.values.yml
done

2025-01-03 17:26 UTC, shimpa1 commented on providerBuild.sh
> +EXECSTART=$(grep "ExecStart=" "$SERVICE_FILE" -A 10)
done

2025-01-04 17:16 UTC, andy108369 requested changes

2025-01-04 17:16 UTC, andy108369 commented on workerNode.sh
> +      kubelet_storage="--kubelet-arg=root-dir=$OPTARG"
Please address

2025-01-04 17:16 UTC, andy108369 commented on k3sAndProviderServices.sh
> +      containerd_storage="--data-dir=$OPTARG"
Please address.

2025-01-04 17:18 UTC, andy108369 requested changes
Please address couple of unresolved comments. Both related to containerd_storag should be renamed into imagefs_dir

Please correct the version of the rest of the rook ceph components, e.g.
https://github.com/chainzero/provider-build-scripts/blob/main/upgrade_k3s.sh

2025-01-04 17:20 UTC, andy108369 commented on providerBuild.sh
> +    helm install --create-namespace -n rook-ceph rook-ceph rook-release/rook-ceph --version 1.14.0 -f ~/provider/rook-ceph-operator.values.yml
There are more places with the old rook ceph version.

2025-01-04 19:28 UTC, shimpa1 commented on workerNode.sh
> +      kubelet_storage="--kubelet-arg=root-dir=$OPTARG"
done

2025-01-04 20:07 UTC, shimpa1 commented on workerNode.sh
> +      kubelet_storage="--kubelet-arg=root-dir=$OPTARG"
done

2025-01-04 20:08 UTC, shimpa1 commented on k3sAndProviderServices.sh
> +      containerd_storage="--data-dir=$OPTARG"
done

2025-01-04 20:36 UTC, andy108369 approved these changes
LGTM

2025-01-04 21:48 UTC, merged